spring:
  datasource:
    #   数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gameplayer?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    initialization-mode: always

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#    # 下划线转驼峰
#    configuration:
#      map-underscore-to-camel-case: true

server:
  port: 8215
